name: Itemsmith
version: '${project.version}'
main: com.kirugoldzzzz.itemsmith.Itemsmith
api-version: '1.21'
folia-supported: true
author: KiruGoldzZz
description: "Éditeur d'objets en jeu"
softdepend: [PlaceholderAPI]
commands:
  item:
    description: Éditer l'objet en main
    usage: /item [edit <champ> ...|undo|info|help]
    permission: itemsmith.admin.item
    aliases: [itemedit, ie, itemeditor, edititem]
permissions:
  itemsmith.admin.item:
    description: Éditer les objets avec /item
    default: op
